image: computermouth/sudeb:stretch

before_script:
  - echo "deb http://ftp.us.debian.org/debian/ stretch main" | sudo tee /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y qemu-user-static live-build sshpass

setup:
  script:
    - sudo lb build
    - ls -lsah
    - sshpass -p '${UPLOAD_PW}' scp live-image-amd64.hybrid.iso ${UPLOAD_UN}@138.68.225.164:cbpp9-amd64-$(date --iso-8601).iso
