image: computermouth/sudeb

before_script:
  - echo "deb http://ftp.us.debian.org/debian/ stretch main" | sudo tee /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y qemu-user-static live-build

setup:
  script:
    - sudo lb build
    - ls -lsah
  artifacts:
    paths:
      - live-image-amd64.hybrid.iso
